# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f16e387feb853b82678e4dba295f139aee8e4ef34c27b77a5475b719b035d7f06ce6328c77ca19236c67e3ea9623ac02c11f57cb1403390de951096e947425a

test:
  secret_key_base: b581479f433754b1a44bb16850d6f5a2b2260fbf1ef7f13cd18476ee712f554801d8a05b75ff2f3674a11f5adf53a41bb44b456da8cb001fcd6fa31c03bdb9eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
